GET http://localhost:8000/api/account HTTP/1.1
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZG1pbiIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE2NzU1Njc5NzYsImV4cCI6MTY3NTY1NDM3Nn0.kK2aq2VQWPLZwJ5YNbd8RPmBnXurqfOG0iw_A8rRGXk
### AUTH: POST LOGIN

POST http://localhost:8000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "123"
}

### AUTH: POST SIGNUP
POST http://localhost:8000/api/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "admin2",
    "username": "admin12",
    "password": "123456"
}