GET http://localhost:8000/api/account HTTP/1.1
Cookie: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZG1pbiIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE2NzM4ODcyODIsImV4cCI6MTY3Mzk3MzY4Mn0.5SVPWQRWbsax7jdXjjLq2Uq41N-3H5kkMjmY2-PWkxQ
### AUTH: POST LOGIN

POST http://localhost:8000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "123"
}

### AUTH: POST SIGNUP
POST http://localhost:8000/api/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "admin2",
    "username": "admin12",
    "password": "123456"
}