GET http://localhost:8000/api/auth/login HTTP/1.1

### AUTH: POST LOGIN

POST http://localhost:8000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "1234"
}

### AUTH: POST SIGNUP
POST http://localhost:8000/api/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "admin2",
    "username": "admin12",
    "password": "123456"
}